const mockStore=new Map<string,any>();const mockKey=(c:string,id:string)=>`${c}/${id}`
jest.mock('../db',()=>({getById:jest.fn(async(c,id)=>{if(!mockStore.has(mockKey(c,id)))throw new Error('missing');return mockStore.get(mockKey(c,id))}),queryAfterId:jest.fn(async()=>[{_id:'community-1',status:'active'}]),query:jest.fn(async(c)=>[...mockStore.entries()].filter(([k])=>k.startsWith(`${c}/`)).map(([,v])=>v)),transactionGetByIdOrNull:jest.fn(async(_tx,c,id)=>mockStore.get(mockKey(c,id))||null),runTransaction:jest.fn(async cb=>cb({collection:(c:string)=>({doc:(id:string)=>({get:async()=>({data:mockStore.get(mockKey(c,id))}),set:async({data}:any)=>{if('_id' in data)throw new Error('document.set cannot update _id');mockStore.set(mockKey(c,id),{_id:id,...structuredClone(data)})},remove:async()=>mockStore.delete(mockKey(c,id))})})}))}))
import{cleanupPostRagReleaseProbe,createPostRagReleaseProbe,readPostRagReleaseProbeStatus,readPostRagReleaseTimerEvidence}from'../post-rag-release-probe'

beforeEach(()=>mockStore.clear())
test('release probe create evidence status cleanup is executable and strictly run-bound',async()=>{
  const probe=await createPostRagReleaseProbe('run-1');expect(mockStore.get(mockKey('post_rag_release_probes','run-1'))).toMatchObject({outboxId:probe.outboxId,postId:probe.postId,status:'active'})
  const hash=mockStore.get(mockKey('post_rag_release_probes','run-1')).triggerIdHash;mockStore.set(mockKey('post_rag_worker_timer_evidence','e1'),{schemaVersion:2,triggerIdHash:hash,invokedAt:'2099-01-01T00:00:00.000Z',outboxIds:[probe.outboxId],v2JobIds:['job-1'],v2CandidateCount:1,v2CompletedCount:1});expect((await readPostRagReleaseTimerEvidence('run-1')).evidence).toMatchObject({source:'timer',outboxIds:[probe.outboxId]})
  mockStore.set(mockKey('post_rag_outbox',probe.outboxId),{_id:probe.outboxId,schemaVersion:2,status:'completed',aggregateId:probe.postId,communityId:probe.communityId,materializedJobId:'job-1'});mockStore.set(mockKey('post_rag_jobs','job-1'),{_id:'job-1',schemaVersion:2,status:'completed',postId:probe.postId,sourceVersion:'sv1'});mockStore.set(mockKey('post_rag_index_state_v2',probe.postId),{_id:probe.postId,postId:probe.postId,schemaVersion:2,state:'active',sourceVersion:'sv1'});expect((await readPostRagReleaseProbeStatus(probe)).complete).toBe(true)
  await expect(readPostRagReleaseProbeStatus({...probe,postId:'cross-run'})).rejects.toThrow(/binding/);expect(await cleanupPostRagReleaseProbe(probe)).toMatchObject({success:true,alreadyCleaned:false});expect(await cleanupPostRagReleaseProbe(probe)).toMatchObject({success:true,alreadyCleaned:true});await expect(readPostRagReleaseTimerEvidence('unknown')).rejects.toThrow(/binding/)
})
